version: 2
updates:
  # Composer configuration
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "DominicLuidold"

  # GitHub Actions configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "DominicLuidold"
