name: CI

on: [push, pull_request]

jobs:
  coding-guidelines:
    name: Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP_CodeSniffer
        run: curl -sfSOL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

      - name: Run PHP_CodeSniffer
        run: php phpcs.phar

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [7.3, 7.4]

    name: Test with PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit
        run: composer run-script phpunit
